[package]
name = "rip_github"
version = "0.1.0"
edition = "2024"
author = "Dennis Lee <dennis.lee@gmx.ch>"
license = "MIT"
description = ""

[workspace]
members = [".", "rip_templating", "rip_templating_macro", "migration", "entity", "server"]

[dependencies]
dotenv = "0.15.0"
# bewerbungs_tool_api = { path = "api" }
migration = { path = "migration" }
entity = { path = "entity" }
server = { path = "server" }
