[package]
name = "rip_git"
version = "0.1.0"
edition = "2024"

[workspace]
members = [".", "templating", "templating_macro", "migration", "entity", "server"]

[dependencies]
dotenv = "0.15.0"
# bewerbungs_tool_api = { path = "api" }
migration = { path = "migration" }
entity = { path = "entity" }
server = { path = "server" }
templating = { path = "templating" }
templating_macro = { path = "templating_macro" }
