[package]
name = "rip_templating"
version = "0.1.2"
edition = "2024"
author = "Dennis Lee <dennis.lee@gmx.ch>"
license = "MIT"
description = "Library for rendering html, templating inside rust code use with axum and htmx support"
readme = "README.md"

[features]
axum = ["dep:axum"]

[dependencies]
rip_templating_macro = "0.1.2"
axum = { version = "0.8.9", optional = true }
