//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "commit_issue")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub issue_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub commit_hash_id: String,
    pub relation_type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::commit_meta::Entity",
        from = "Column::CommitHashId",
        to = "super::commit_meta::Column::HashId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    CommitMeta,
    #[sea_orm(
        belongs_to = "super::issue::Entity",
        from = "Column::IssueId",
        to = "super::issue::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Issue,
}

impl Related<super::commit_meta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommitMeta.def()
    }
}

impl Related<super::issue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Issue.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
