//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "commit_meta")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub hash_id: String,
    pub author: String,
    #[sea_orm(column_type = "Text")]
    pub message: String,
    pub timestamp: DateTimeUtc,
    pub refs: String,
    pub repo_id: i32,
    pub author_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::author::Entity",
        from = "Column::AuthorId",
        to = "super::author::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Author,
    #[sea_orm(has_many = "super::commit_issue::Entity")]
    CommitIssue,
    #[sea_orm(has_many = "super::commit_tag::Entity")]
    CommitTag,
    #[sea_orm(has_many = "super::issue_event::Entity")]
    IssueEvent,
    #[sea_orm(
        belongs_to = "super::repo::Entity",
        from = "Column::RepoId",
        to = "super::repo::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Repo,
}

impl Related<super::author::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Author.def()
    }
}

impl Related<super::commit_issue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommitIssue.def()
    }
}

impl Related<super::commit_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommitTag.def()
    }
}

impl Related<super::issue_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueEvent.def()
    }
}

impl Related<super::repo::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Repo.def()
    }
}

impl Related<super::issue::Entity> for Entity {
    fn to() -> RelationDef {
        super::commit_issue::Relation::Issue.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::commit_issue::Relation::CommitMeta.def().rev())
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        super::commit_tag::Relation::Tag.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::commit_tag::Relation::CommitMeta.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
