//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "issue")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub status: String,
    pub priority: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub assignee_id: i32,
    pub reporter_id: i32,
    pub repo_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::commit_issue::Entity")]
    CommitIssue,
    #[sea_orm(has_many = "super::issue_comment::Entity")]
    IssueComment,
    #[sea_orm(has_many = "super::issue_event::Entity")]
    IssueEvent,
    #[sea_orm(
        belongs_to = "super::repo::Entity",
        from = "Column::RepoId",
        to = "super::repo::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Repo,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::ReporterId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User2,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::AssigneeId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    User1,
}

impl Related<super::commit_issue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommitIssue.def()
    }
}

impl Related<super::issue_comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueComment.def()
    }
}

impl Related<super::issue_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueEvent.def()
    }
}

impl Related<super::repo::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Repo.def()
    }
}

impl Related<super::commit_meta::Entity> for Entity {
    fn to() -> RelationDef {
        super::commit_issue::Relation::CommitMeta.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::commit_issue::Relation::Issue.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
