//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "issue_event")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub issue_id: i32,
    pub event_type: String,
    pub created_at: DateTimeUtc,
    pub actor_id: i32,
    pub comment_id: i32,
    pub commit_hash_id: String,
    pub from_status: String,
    pub to_status: String,
    pub assignee_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::commit_meta::Entity",
        from = "Column::CommitHashId",
        to = "super::commit_meta::Column::HashId",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    CommitMeta,
    #[sea_orm(
        belongs_to = "super::issue::Entity",
        from = "Column::IssueId",
        to = "super::issue::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Issue,
    #[sea_orm(
        belongs_to = "super::issue_comment::Entity",
        from = "Column::CommentId",
        to = "super::issue_comment::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    IssueComment,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::AssigneeId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    User2,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::ActorId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    User1,
}

impl Related<super::commit_meta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommitMeta.def()
    }
}

impl Related<super::issue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Issue.def()
    }
}

impl Related<super::issue_comment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssueComment.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
