//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod author;
pub mod branch;
pub mod commit_issue;
pub mod commit_meta;
pub mod commit_tag;
pub mod issue;
pub mod issue_comment;
pub mod issue_event;
pub mod repo;
pub mod tag;
pub mod user;
