//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::author::Entity as Author;
pub use super::branch::Entity as Branch;
pub use super::commit_issue::Entity as CommitIssue;
pub use super::commit_meta::Entity as CommitMeta;
pub use super::commit_tag::Entity as CommitTag;
pub use super::issue::Entity as Issue;
pub use super::issue_comment::Entity as IssueComment;
pub use super::issue_event::Entity as IssueEvent;
pub use super::repo::Entity as Repo;
pub use super::tag::Entity as Tag;
pub use super::user::Entity as User;
