//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tag")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::commit_tag::Entity")]
    CommitTag,
}

impl Related<super::commit_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommitTag.def()
    }
}

impl Related<super::commit_meta::Entity> for Entity {
    fn to() -> RelationDef {
        super::commit_tag::Relation::CommitMeta.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::commit_tag::Relation::Tag.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
